name: proto-lens
version: "0.7.1.3"
synopsis: A lens-based implementation of protocol buffers in Haskell.
description: >
  The proto-lens library provides an API for protocol buffers using modern
  Haskell language and library patterns.  Specifically, it provides:
   
  * Composable field accessors via lenses
   
  * Simple field name resolution/overloading via type-level literals
   
  * Type-safe reflection and encoding/decoding of messages via GADTs

github: google/proto-lens/proto-lens
license: BSD3
author: Judah Jacobson
maintainer: proto-lens@googlegroups.com
copyright: Google Inc.
category: Data
extra-source-files:
  - Changelog.md

library:
  source-dirs: src

  other-modules:
    - Data.ProtoLens.Encoding.Parser.Internal
    - Data.ProtoLens.TextFormat.Parser
  dependencies:
    - base >= 4.10 && < 4.19
    - bytestring >= 0.10 && < 0.13
    - containers >= 0.5 && < 0.7
    - deepseq == 1.4.*
    - ghc-prim >= 0.4 && < 0.11
    - lens-family >= 1.2 && < 2.2
    - parsec == 3.1.*
    - pretty == 1.1.*
    - primitive >= 0.6 && < 0.9
    - profunctors >= 5.2 && < 6.0
    - tagged == 0.8.*
    - text >= 1.2 && < 2.2
    - transformers >= 0.4 && < 0.7
    - vector >= 0.11 && < 0.14

tests:
  parser_test:
    main: parser_test.hs
    source-dirs: tests
    dependencies:
    - base
    - bytestring
    - proto-lens
    - QuickCheck
    - tasty
    - tasty-quickcheck

  growing_test:
    main: growing_test.hs
    source-dirs: tests
    dependencies:
    - base
    - vector
    - proto-lens
    - QuickCheck
    - tasty
    - tasty-quickcheck
