name: proto-lens
version: "0.3.1.0"
synopsis: A lens-based implementation of protocol buffers in Haskell.
description: >
  The proto-lens library provides to protocol buffers using modern
  Haskell language and library patterns.  Specifically, it provides:
   
  * Composable field accessors via lenses
   
  * Simple field name resolution/overloading via type-level literals
   
  * Type-safe reflection and encoding/decoding of messages via GADTs

github: google/proto-lens/proto-lens
license: BSD3
author: Judah Jacobson
maintainer: proto-lens@googlegroups.com
copyright: Google Inc.
category: Data
extra-source-files:
  - Changelog.md

# Make the corresponding .proto files available for other packages to import.
# Usually this happens automatically as part of Data.ProtoLens.Setup,
# but because of bootstrapping we don't use that module here.
data-files:
  - proto-lens-imports/google/protobuf/descriptor.proto
  - proto-lens-imports/google/protobuf/compiler/plugin.proto

library:
  source-dirs: src
  exposed-modules:
    - Data.ProtoLens
    - Data.ProtoLens.Encoding
    - Data.ProtoLens.Encoding.Wire
    - Data.ProtoLens.Message
    - Data.ProtoLens.Message.Enum
    - Data.ProtoLens.Service.Types
    - Data.ProtoLens.TextFormat
    - Proto.Google.Protobuf.Compiler.Plugin
    - Proto.Google.Protobuf.Compiler.Plugin_Fields
    - Proto.Google.Protobuf.Descriptor
    - Proto.Google.Protobuf.Descriptor_Fields
  other-modules:
    - Data.ProtoLens.Encoding.Bytes
    - Data.ProtoLens.TextFormat.Parser
  dependencies:
    - attoparsec == 0.13.*
    - base >= 4.8 && < 4.12
    - bytestring == 0.10.*
    - containers == 0.5.*
    - deepseq == 1.4.*
    - data-default-class >= 0.0 && < 0.2
    - lens-family == 1.2.*
    - lens-labels == 0.2.*
    - parsec == 3.1.*
    - pretty == 1.1.*
    - text == 1.2.*
    - transformers >= 0.4 && < 0.6
    - void == 0.7.*
