name: proto-lens
version: "0.4.0.1"
synopsis: A lens-based implementation of protocol buffers in Haskell.
description: >
  The proto-lens library provides an API for protocol buffers using modern
  Haskell language and library patterns.  Specifically, it provides:
   
  * Composable field accessors via lenses
   
  * Simple field name resolution/overloading via type-level literals
   
  * Type-safe reflection and encoding/decoding of messages via GADTs

github: google/proto-lens/proto-lens
license: BSD3
author: Judah Jacobson
maintainer: proto-lens@googlegroups.com
copyright: Google Inc.
category: Data
extra-source-files:
  - Changelog.md

# Make the corresponding .proto files available for other packages to import.
# Usually this happens automatically as part of Data.ProtoLens.Setup,
# but because of bootstrapping we don't use that module here.
data-files:
  - proto-lens-imports/google/protobuf/descriptor.proto
  - proto-lens-imports/google/protobuf/compiler/plugin.proto

library:
  source-dirs: src

  other-modules:
    - Data.ProtoLens.Encoding.Parser.Internal
    - Data.ProtoLens.TextFormat.Parser
  dependencies:
    - base >= 4.9 && < 4.13
    - bytestring == 0.10.*
    - containers >= 0.5 && < 0.7
    - deepseq == 1.4.*
    - lens-family == 1.2.*
    - lens-labels == 0.3.*
    - parsec == 3.1.*
    - pretty == 1.1.*
    - primitive == 0.6.*
    - text == 1.2.*
    - transformers >= 0.4 && < 0.6
    - vector >= 0.11 && < 0.13
    - void == 0.7.*

tests:
  parser_test:
    main: parser_test.hs
    source-dirs: tests
    dependencies:
    - base
    - bytestring
    - proto-lens
    - QuickCheck
    - test-framework
    - test-framework-quickcheck2
