name: proto-lens
version: "0.4.0.1"
synopsis: A lens-based implementation of protocol buffers in Haskell.
description: >
  The proto-lens library provides an API for protocol buffers using modern
  Haskell language and library patterns.  Specifically, it provides:
   
  * Composable field accessors via lenses
   
  * Simple field name resolution/overloading via type-level literals
   
  * Type-safe reflection and encoding/decoding of messages via GADTs

github: google/proto-lens/proto-lens
license: BSD3
author: Judah Jacobson
maintainer: proto-lens@googlegroups.com
copyright: Google Inc.
category: Data
extra-source-files:
  - Changelog.md

# Make the corresponding .proto files available for other packages to import.
# Usually this happens automatically as part of Data.ProtoLens.Setup,
# but because of bootstrapping we don't use that module here.
data-files:
  - proto-lens-imports/google/protobuf/descriptor.proto
  - proto-lens-imports/google/protobuf/compiler/plugin.proto

flags:
  generated-encoding:
    description: >
        Enable the codepath for generated encodings.  Currently
        incomplete and experimental.
    manual: True
    default: False

library:
  source-dirs: src
  exposed-modules:
    - Data.ProtoLens
    - Data.ProtoLens.Combinators
    - Data.ProtoLens.Default
    - Data.ProtoLens.Encoding
    - Data.ProtoLens.Encoding.Wire
    - Data.ProtoLens.Message
    - Data.ProtoLens.Message.Enum
    - Data.ProtoLens.Service.Types
    - Data.ProtoLens.TextFormat
    - Proto.Google.Protobuf.Compiler.Plugin
    - Proto.Google.Protobuf.Compiler.Plugin_Fields
    - Proto.Google.Protobuf.Descriptor
    - Proto.Google.Protobuf.Descriptor_Fields
    # Expose this module so it can be used by proto-lens-protoc.
    # Currently, the generated encoding doesn't work well enough to be
    # used by it.
    - Data.ProtoLens.Encoding.Reflected
  when:
    - condition: flag(generated-encoding)
      then:
        cpp-options: -DGENERATED_ENCODING=1
      else:
        cpp-options: -DGENERATED_ENCODING=0

  other-modules:
    - Data.ProtoLens.Encoding.Bytes
    - Data.ProtoLens.TextFormat.Parser
    - Data.ProtoLens.Encoding.Reflected.Wire
  dependencies:
    - attoparsec == 0.13.*
    - base >= 4.9 && < 4.13
    - bytestring == 0.10.*
    - containers >= 0.5 && < 0.7
    - deepseq == 1.4.*
    - lens-family == 1.2.*
    - lens-labels == 0.3.*
    - parsec == 3.1.*
    - pretty == 1.1.*
    - text == 1.2.*
    - transformers >= 0.4 && < 0.6
    - void == 0.7.*
