name: proto-lens-protoc
version: '0.5.0.0'
synopsis: Protocol buffer compiler for the proto-lens library.
description: >
  Turn protocol buffer files (.proto) into Haskell files (.hs) which
  can be used with the proto-lens package.
 
  The library component of this package contains compiler code (namely
  Data.ProtoLens.Compiler.*) is not guaranteed to have stable APIs.'
category: Data
author: Judah Jacobson
maintainer: proto-lens@googlegroups.com
github: google/proto-lens/proto-lens-protoc
copyright: Google Inc.
license: BSD3
extra-source-files:
  - Changelog.md

dependencies:
  - base >= 4.10 && < 4.13
  - bytestring == 0.10.*
  - containers >= 0.5 && < 0.7
  - lens-family == 1.2.*
  - proto-lens == 0.5.*
  - text == 1.2.*


library:
  source-dirs: src
  dependencies:
    - filepath >= 1.4 && < 1.6
    - haskell-src-exts >= 1.18 && < 1.22
    - pretty == 1.1.*
  exposed-modules:
    - Data.ProtoLens.Compiler.Combinators
    - Data.ProtoLens.Compiler.Definitions
    - Data.ProtoLens.Compiler.Generate
    - Data.ProtoLens.Compiler.Plugin

executables:
  proto-lens-protoc:
    main: protoc-gen-haskell.hs
    source-dirs: app
    dependencies:
      - proto-lens-protoc
