name: proto-lens-protoc
version: '0.3.1.1'
synopsis: Protocol buffer compiler for the proto-lens library.
description: >
  Turn protocol buffer files (.proto) into Haskell files (.hs) which
  can be used with the proto-lens package.
 
  The library component of this package contains compiler code (namely
  Data.ProtoLens.Compiler.*) is not guaranteed to have stable APIs.'
category: Data
author: Judah Jacobson
maintainer: proto-lens@googlegroups.com
github: google/proto-lens/proto-lens-protoc
copyright: Google Inc.
license: BSD3
extra-source-files:
  - Changelog.md

dependencies:
  - base >= 4.9 && < 4.12
  - bytestring == 0.10.*
  - containers == 0.5.*
  - data-default-class >= 0.0 && < 0.2
  - deepseq == 1.4.*
  - filepath >= 1.4 && < 1.6
  - haskell-src-exts >= 1.17 && < 1.21
  - lens-family == 1.2.*
  - proto-lens == 0.3.*
  - text == 1.2.*


library:
  source-dirs: src
  dependencies:
    - Cabal >= 1.22 && < 2.3
    - directory >= 1.2 && < 1.4
    - lens-labels == 0.2.*
    - pretty == 1.1.*
    - process >= 1.2 && < 1.7
    - temporary == 1.2.*
  exposed-modules:
    - Data.ProtoLens.Compiler.Combinators
    - Data.ProtoLens.Compiler.Definitions
    - Data.ProtoLens.Compiler.Generate
    - Data.ProtoLens.Compiler.Plugin
    - Data.ProtoLens.Setup
  reexported-modules:
    # Modules that are needed by the generated Haskell files.
    # For forwards compatibility, reexport them as new module names so that
    # other packages don't accidentally write non-generated code that
    # relies on these modules being reexported by proto-lens-protoc.
    - Prelude as Data.ProtoLens.Reexport.Prelude,
    - Data.Int as Data.ProtoLens.Reexport.Data.Int,
    - Data.Word as Data.ProtoLens.Reexport.Data.Word,
    - Data.ByteString as Data.ProtoLens.Reexport.Data.ByteString,
    - Data.ByteString.Char8 as Data.ProtoLens.Reexport.Data.ByteString.Char8,
    - Data.Default.Class as Data.ProtoLens.Reexport.Data.Default.Class,
    - Data.Map as Data.ProtoLens.Reexport.Data.Map,
    - Data.ProtoLens as Data.ProtoLens.Reexport.Data.ProtoLens,
    - Data.ProtoLens.Service.Types as Data.ProtoLens.Reexport.Data.ProtoLens.Service.Types,
    - Data.ProtoLens.Message.Enum as Data.ProtoLens.Reexport.Data.ProtoLens.Message.Enum,
    - Data.Text as Data.ProtoLens.Reexport.Data.Text,
    - Lens.Family2 as Data.ProtoLens.Reexport.Lens.Family2,
    - Lens.Family2.Unchecked as Data.ProtoLens.Reexport.Lens.Family2.Unchecked,
    - Lens.Labels as Data.ProtoLens.Reexport.Lens.Labels,
    - Lens.Labels.Prism as Data.ProtoLens.Reexport.Lens.Labels.Prism,
    - Text.Read as Data.ProtoLens.Reexport.Text.Read

executables:
  proto-lens-protoc:
    main: protoc-gen-haskell.hs
    source-dirs: app
    dependencies:
      - proto-lens-protoc

flags:
  only-executable:
    description: Only build the executable.  Used for bootstrapping.
    manual: false
    default: false
