resolver: lts-10.3
packages:
- lens-labels
- proto-lens
- proto-lens-protoc
- proto-lens-protobuf-types
- proto-lens-arbitrary
- proto-lens-combinators
- proto-lens-optparse
- proto-lens-tests-dep
- proto-lens-tests
- proto-lens-benchmarks
