resolver: lts-11.7
packages:
- discrimination-ieee754
- lens-labels
- proto-lens
- proto-lens-protoc
- proto-lens-protobuf-types
- proto-lens-arbitrary
- proto-lens-combinators
- proto-lens-optparse
- proto-lens-tests-dep
- proto-lens-tests
- proto-lens-benchmarks
- proto-lens-discrimination

extra-deps:
- discrimination-0.3
- promises-0.3
