resolver: lts-14.4
packages:
- discrimination-ieee754
- proto-lens
- proto-lens-arbitrary
- proto-lens-benchmarks
- proto-lens-discrimination
- proto-lens-optparse
- proto-lens-protobuf-types
- proto-lens-protoc
- proto-lens-runtime
- proto-lens-setup
- proto-lens-tests
- proto-lens-tests-dep
extra-deps:
- ghc-source-gen-0.4.0.0
- discrimination-0.4
- promises-0.3
- primitive-0.6.4.0  # For discrimination-0.4 on older LTSes

ghc-options:
  "$locals": -Wall -Werror
