name: proto-lens-discrimination
version: '0.1.1.1'
synopsis: Support for using proto-lens types with http://hackage.haskell.org/package/discrimination.
description: >
  Reflection-based implementations of Sort for proto-lens'
  generated types.
category: Data
author: Andrew Pritchard
maintainer: awpr+protolens@google.com
copyright: Google Inc.
license: BSD3
github: google/proto-lens/proto-lens-discrimination
extra-source-files:
  - tests/*.proto

custom-setup:
  dependencies:
    - base >= 4.10 && < 4.13
    - Cabal
    - proto-lens-setup >= 0.4 && < 0.5

build-tools: proto-lens-protoc

dependencies:
  - base >= 4.10 && < 4.13
  - bytestring == 0.10.*
  - contravariant >= 1.3 && < 1.6
  - containers >= 0.5 && < 0.7
  - discrimination >= 0.3 && < 0.5
  - discrimination-ieee754 == 0.1.*
  - lens-family == 1.2.*
  - proto-lens == 0.5.*
  - proto-lens-runtime == 0.5.*
  - text == 1.2.*

library:
  source-dirs: src
  exposed-modules:
    - Data.ProtoLens.Sort
    - Data.ProtoLens.Group
    - Data.ProtoLens.Discrimination

tests:

  discrimination_test:
    main: disc_test.hs
    source-dirs: tests
    dependencies:
      - HUnit >= 1.3 && < 1.7
      - proto-lens-arbitrary >= 0.1 && < 0.2
      - proto-lens-discrimination
      - test-framework == 0.8.*
      - test-framework-hunit == 0.3.*
      - test-framework-quickcheck2 == 0.3.*
    generated-other-modules:
      - Proto.Enum
      - Proto.Enum_Fields
      - Proto.Map
      - Proto.Map_Fields
