name: proto-lens-discrimination
version: '0.1.1.0'
synopsis: Support for using proto-lens types with http://hackage.haskell.org/package/discrimination.
description: >
  Reflection-based implementations of Sort for proto-lens'
  generated types.
category: Data
author: Andrew Pritchard
maintainer: awpr+protolens@google.com
copyright: Google Inc.
license: BSD3
github: google/proto-lens/proto-lens-discrimination
extra-source-files:
  - tests/*.proto

custom-setup:
  dependencies:
    - base >= 4.9 && < 4.13
    - Cabal
    - proto-lens-protoc == 0.3.*

dependencies:
  - base >= 4.9 && < 4.13
  - data-default >= 0.5 && < 0.8
  - bytestring == 0.10.*
  - contravariant >= 1.3 && < 1.5
  - containers >= 0.5 && < 0.6
  - discrimination >= 0.3 && < 0.4
  - discrimination-ieee754 == 0.1.*
  - lens-family == 1.2.*
  - proto-lens >= 0.3 && < 0.4
  - proto-lens-protoc >= 0.3 && < 0.4
  - text == 1.2.*

library:
  source-dirs: src
  exposed-modules:
    - Data.ProtoLens.Sort
    - Data.ProtoLens.Group
    - Data.ProtoLens.Discrimination

tests:

  discrimination_test:
    main: disc_test.hs
    source-dirs: tests
    dependencies:
      - HUnit >= 1.3 && < 1.7
      - proto-lens-arbitrary >= 0.1 && < 0.2
      - proto-lens-discrimination
      - test-framework == 0.8.*
      - test-framework-hunit == 0.3.*
      - test-framework-quickcheck2 == 0.3.*
    other-modules:
      - Proto.Enum
      - Proto.Enum_Fields
    # Manually list autogenerated modules, to avoid hpack
    # requiring `cabal-version: >= 2.0`.
    verbatim:
      - |
        autogen-modules:
          Proto.Enum
          Proto.Enum_Fields
