resolver: lts-12.7
packages:
- person
- coffee-order

- extra-dep: true
  location:
    '..'
  subdirs:
    - lens-labels
    - proto-lens
    - proto-lens-protoc
    - proto-lens-runtime
    - proto-lens-setup
