resolver: lts-12.7
packages:
- person
- coffee-order

- extra-dep: true
  location:
    '..'
  subdirs:
    - proto-lens
    - proto-lens-protoc
    - proto-lens-runtime
    - proto-lens-setup

extra-deps:
- ghc-source-gen-0.3.0.0
