name:                coffee-order
version:             0.1.0.2
homepage:            https://github.com/google/proto-tutorial/coffee-order#readme
license:             BSD3
author:              Fintan Halpenny
maintainer:          fintan.halpenny@gmail.com
copyright:           2017 Google Inc.
category:            Data
extra-source-files:
- README.md
- proto/**/*.proto

custom-setup:
  dependencies:
    - base
    - Cabal
    - proto-lens-setup

build-tools: proto-lens-protoc:proto-lens-protoc

dependencies:
  - base >= 4.10 && < 5
  - microlens
  - proto-lens
  - proto-lens-runtime
  - text

executables:
  gimme-coffee:
    other-modules:
      - Proto.Coffee.Order
      - Proto.Coffee.Order_Fields
    source-dirs:      src
    main:             Main.hs
