name: proto-lens-arbitrary
version: "0.1.2.7"
synopsis: Arbitrary instances for proto-lens.
description: >
  The proto-lens-arbitrary allows generating arbitrary messages for
  use with QuickCheck.
category: Data
author: Aden Grue
maintainer: agrue+protolens@google.com
copyright: Google Inc.
license: BSD3
github: google/proto-lens/proto-lens-arbitrary
extra-source-files:
  - Changelog.md

dependencies:
  - proto-lens >= 0.4 && < 0.6
  - base >= 4.10 && < 4.13
  - bytestring == 0.10.*
  - containers >= 0.5 && < 0.7
  - text == 1.2.*
  - lens-family == 1.2.*
  - QuickCheck >= 2.8 && < 2.14

library:
  source-dirs: src
  exposed-modules:
    - Data.ProtoLens.Arbitrary
