name: lens-labels
version: "0.2.0.1"
synopsis: Integration of lenses with OverloadedLabels.
description: >
  Provides a framework to integrate lenses with GHC's OverloadedLabels
  extension.
github: google/proto-lens/lens-labels
license: BSD3
author: Judah Jacobson
maintainer: proto-lens@googlegroups.com
copyright: Google Inc.
category: Data
extra-source-files:
  - Changelog.md

library:
  source-dirs: src
  exposed-modules:
    - Lens.Labels
    - Lens.Labels.Unwrapped
    - Lens.Labels.Prism
  dependencies:
    - base >= 4.8 && < 4.12
    - ghc-prim >= 0.4 && < 0.6
    - profunctors >= 5.2
    - tagged >= 0.8
