#!/usr/bin/env bash

shopt -s globstar

set -x
stack exec -- protoc \
  --plugin=protoc-gen-haskell=`which proto-lens-protoc` \
  --haskell_out=$PWD/src \
  --proto_path=$PWD/proto-src/src \
  $PWD/proto-src/src/google/protobuf/any.proto \
  $PWD/proto-src/src/google/protobuf/api.proto \
  $PWD/proto-src/src/google/protobuf/descriptor.proto \
  $PWD/proto-src/src/google/protobuf/duration.proto \
  $PWD/proto-src/src/google/protobuf/empty.proto \
  $PWD/proto-src/src/google/protobuf/field_mask.proto \
  $PWD/proto-src/src/google/protobuf/source_context.proto \
  $PWD/proto-src/src/google/protobuf/struct.proto \
  $PWD/proto-src/src/google/protobuf/timestamp.proto \
  $PWD/proto-src/src/google/protobuf/type.proto \
  $PWD/proto-src/src/google/protobuf/wrappers.proto \
  $PWD/proto-src/src/google/protobuf/compiler/plugin.proto
