name: proto-lens-protobuf-types
version: '0.3.0.2'
synopsis: Basic protocol buffer message types.
description: >
  This package provides bindings standard protocol message types,
  for use with the proto-lens library.
category: Data
author: Judah Jacobson
maintainer: proto-lens@googlegroups.com
copyright: Google Inc.
license: BSD3
github: google/proto-lens/proto-lens-protobuf-types
extra-source-files:
  - Changelog.md
  - proto-src/google/protobuf/any.proto
  - proto-src/google/protobuf/duration.proto
  - proto-src/google/protobuf/wrappers.proto
  - proto-src/google/protobuf/timestamp.proto

custom-setup:
  dependencies:
    - base >= 4.9 && < 4.12
    - Cabal
    - proto-lens-protoc == 0.3.*

dependencies:
  - base >= 4.9 && < 4.12
  - lens-labels == 0.2.*
  - proto-lens == 0.3.*
  - proto-lens-protoc-rt == 0.3.*
  - text == 1.2.*

library:
  source-dirs: src
  exposed-modules:
    - Data.ProtoLens.Any
    - Proto.Google.Protobuf.Any
    - Proto.Google.Protobuf.Any_Fields
    - Proto.Google.Protobuf.Duration
    - Proto.Google.Protobuf.Duration_Fields
    - Proto.Google.Protobuf.Wrappers
    - Proto.Google.Protobuf.Wrappers_Fields
    - Proto.Google.Protobuf.Timestamp
    - Proto.Google.Protobuf.Timestamp_Fields
  # Manually list autogenerated modules, to avoid hpack
  # requiring `cabal-version: >= 2.0`.
  verbatim:
    - |
      autogen-modules:
        Proto.Google.Protobuf.Any
        Proto.Google.Protobuf.Any_Fields
        Proto.Google.Protobuf.Duration
        Proto.Google.Protobuf.Duration_Fields
        Proto.Google.Protobuf.Wrappers
        Proto.Google.Protobuf.Wrappers_Fields
        Proto.Google.Protobuf.Timestamp
        Proto.Google.Protobuf.Timestamp_Fields
