name: proto-lens-protobuf-types
version: '0.7.2.0'
synopsis: Basic protocol buffer message types.
description: >
  This package provides bindings standard protocol message types,
  for use with the proto-lens library.
category: Data
author: Judah Jacobson
maintainer: proto-lens@googlegroups.com
copyright: Google Inc.
license: BSD3
github: google/proto-lens/proto-lens-protobuf-types
extra-source-files:
  - Changelog.md
  - proto-src/google/protobuf/any.proto
  - proto-src/google/protobuf/api.proto
  - proto-src/google/protobuf/compiler/plugin.proto
  - proto-src/google/protobuf/descriptor.proto
  - proto-src/google/protobuf/duration.proto
  - proto-src/google/protobuf/empty.proto
  - proto-src/google/protobuf/field_mask.proto
  - proto-src/google/protobuf/source_context.proto
  - proto-src/google/protobuf/struct.proto
  - proto-src/google/protobuf/timestamp.proto
  - proto-src/google/protobuf/type.proto
  - proto-src/google/protobuf/wrappers.proto

custom-setup:
  dependencies:
    - base >= 4.10 && < 4.19
    - Cabal >= 3 && < 3.12
    - proto-lens-setup == 0.4.*

build-tools: proto-lens-protoc:proto-lens-protoc

dependencies:
  - base >= 4.10 && < 4.19
  - lens-family >= 1.2 && < 2.2
  - proto-lens == 0.7.*
  - proto-lens-runtime == 0.7.*
  - text >= 1.2 && < 2.2

library:
  source-dirs: src
  exposed-modules:
    - Data.ProtoLens.Any
    - Data.ProtoLens.Descriptor
  generated-exposed-modules:
    - Proto.Google.Protobuf.Any
    - Proto.Google.Protobuf.Any_Fields
    - Proto.Google.Protobuf.Api
    - Proto.Google.Protobuf.Api_Fields
    - Proto.Google.Protobuf.Compiler.Plugin
    - Proto.Google.Protobuf.Compiler.Plugin_Fields
    - Proto.Google.Protobuf.Descriptor
    - Proto.Google.Protobuf.Descriptor_Fields
    - Proto.Google.Protobuf.Duration
    - Proto.Google.Protobuf.Duration_Fields
    - Proto.Google.Protobuf.Empty
    - Proto.Google.Protobuf.Empty_Fields
    - Proto.Google.Protobuf.FieldMask
    - Proto.Google.Protobuf.FieldMask_Fields
    - Proto.Google.Protobuf.SourceContext
    - Proto.Google.Protobuf.SourceContext_Fields
    - Proto.Google.Protobuf.Struct
    - Proto.Google.Protobuf.Struct_Fields
    - Proto.Google.Protobuf.Timestamp
    - Proto.Google.Protobuf.Timestamp_Fields
    - Proto.Google.Protobuf.Type
    - Proto.Google.Protobuf.Type_Fields
    - Proto.Google.Protobuf.Wrappers
    - Proto.Google.Protobuf.Wrappers_Fields

  # Prevent hpack from putting Paths_* in the other-modules.
  # Otherwise, "cabal check" complains (preventing upload to Hackage)
  # because it expects it to be listed in autogen-modules.
  # For details, see https://github.com/sol/hpack/issues/303.
  when:
  - condition: false
    other-modules: Paths_proto_lens_protobuf_types
