on:
  - push
  - pull_request
name: cabal build

permissions:
  contents: read

jobs:
  runhaskell:
    name: cabal test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: ['9.12', '9.14']
        cabal: ['3.16']

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: haskell-actions/setup@0f8e8c99d88aeb3fbfd523f1ef2c6f762d10d64d # v2.12.1
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - run: cabal build --dependencies-only --project-file ghc${{ matrix.ghc }}.cabal.project all
      - run: cabal build                     --project-file ghc${{ matrix.ghc }}.cabal.project all
      - run: cabal test                      --project-file ghc${{ matrix.ghc }}.cabal.project all
